[package]
name = "page-table"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3.2"
cfg-if = "1.0.0"
log = "0.4.14"


[features]
default = ["rv64"]
rv32 = []
rv64 = []