[package]
name = "page-table"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memory_addr = { git ="https://github.com/os-module/memory_addr" }
bitflags = "1.3.2"
log = "0"
